<a href="https://colab.research.google.com/github/Gaukhar-ai/Gaukhar.Diamond.github/blob/master/Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a = np.array([[0, 1,2,3], [4,5,6,7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [3]:
#array is a function. array() - returns a data structure in the numpy array format

In [4]:
a.shape

(2, 4)

In [5]:
a[1,3]

7

In [7]:
a[1,2] = 8
a

array([[0, 1, 2, 3],
       [4, 5, 8, 7]])

In [8]:
a[0]

array([0, 1, 2, 3])

In [9]:
a[1]

array([4, 5, 8, 7])

In [11]:
b = np.array([3,5])
b

array([3, 5])

In [14]:
import random

In [16]:
prob = random.random()
print (prob)

0.7136013445624777


In [18]:
number = random.randint(1,6)
print(number)

3


In [19]:
import numpy as np

In [20]:
np.random.randint(1,6,(4,6))

array([[5, 4, 1, 4, 4, 3],
       [2, 5, 1, 1, 3, 3],
       [2, 4, 5, 1, 1, 4],
       [1, 2, 4, 4, 1, 4]])